import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const planets = [
  {
    name: "Mercury",
    slug: "mercury",
    type: "terrestrial",
    description: "The smallest planet in the Solar System and the closest world to the Sun.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg",
    massKg: 3.3e23,
    diameterKm: 4879,
    gravityMs2: 3.7,
    distanceFromSunAu: 0.387,
    orbitalPeriodDays: 88,
    rotationPeriodHours: 1407.6,
    avgTempCelsius: 167,
    atmosphere: ["O2", "Na", "H2"],
    numberOfMoons: 0,
    hasRings: false,
    discoveredBy: "Known in antiquity",
    isVisible: true,
    aiFunFacts: [
      "Mercury has a solar day that lasts longer than its year.",
      "Its cratered surface records billions of years of impacts.",
      "Mercury has no natural moons and almost no atmosphere.",
    ],
  },
  {
    name: "Venus",
    slug: "venus",
    type: "terrestrial",
    description: "The hottest planet in the Solar System, wrapped in a dense carbon dioxide atmosphere.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg",
    massKg: 4.87e24,
    diameterKm: 12104,
    gravityMs2: 8.87,
    distanceFromSunAu: 0.723,
    orbitalPeriodDays: 225,
    rotationPeriodHours: 5832.5,
    avgTempCelsius: 464,
    atmosphere: ["CO2", "N2", "SO2"],
    numberOfMoons: 0,
    hasRings: false,
    discoveredBy: "Known in antiquity",
    isVisible: true,
    aiFunFacts: [
      "Venus rotates backward compared with most planets.",
      "One day on Venus is longer than one Venus year.",
      "Venus is the brightest natural object in the night sky after the Moon.",
    ],
  },
  {
    name: "Earth",
    slug: "earth",
    type: "terrestrial",
    description: "The blue planet and the only known world that supports life.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/97/The_Earth_seen_from_Apollo_17.jpg",
    massKg: 5.97e24,
    diameterKm: 12742,
    gravityMs2: 9.81,
    distanceFromSunAu: 1,
    orbitalPeriodDays: 365.25,
    rotationPeriodHours: 24,
    avgTempCelsius: 15,
    atmosphere: ["N2", "O2", "Ar", "CO2"],
    numberOfMoons: 1,
    hasRings: false,
    isVisible: true,
    aiFunFacts: [
      "Earth is the only known planet with stable liquid water on its surface.",
      "Earth's magnetic field helps shield the planet from solar radiation.",
      "Earth has one unusually large natural moon compared with its size.",
    ],
  },
  {
    name: "Mars",
    slug: "mars",
    type: "terrestrial",
    description: "The Red Planet, home to the tallest volcano and one of the deepest canyon systems in the Solar System.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/OSIRIS_Mars_true_color.jpg",
    massKg: 6.39e23,
    diameterKm: 6779,
    gravityMs2: 3.72,
    distanceFromSunAu: 1.524,
    orbitalPeriodDays: 687,
    rotationPeriodHours: 24.6,
    avgTempCelsius: -60,
    atmosphere: ["CO2", "N2", "Ar"],
    numberOfMoons: 2,
    hasRings: false,
    discoveredBy: "Known in antiquity",
    isVisible: true,
    aiFunFacts: [
      "Olympus Mons on Mars is the largest volcano in the Solar System.",
      "Mars looks red because iron minerals in its soil oxidize.",
      "Valles Marineris is a canyon system thousands of kilometers long.",
    ],
  },
  {
    name: "Jupiter",
    slug: "jupiter",
    type: "gas_giant",
    description: "The largest planet in the Solar System, famous for the Great Red Spot.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg",
    massKg: 1.9e27,
    diameterKm: 139820,
    gravityMs2: 24.79,
    distanceFromSunAu: 5.203,
    orbitalPeriodDays: 4333,
    rotationPeriodHours: 9.9,
    avgTempCelsius: -110,
    atmosphere: ["H2", "He", "CH4", "NH3"],
    numberOfMoons: 95,
    hasRings: true,
    discoveredBy: "Known in antiquity",
    isVisible: true,
    aiFunFacts: [
      "Jupiter is so large that all the other planets could fit inside it.",
      "The Great Red Spot is a giant storm that has lasted for centuries.",
      "Europa, one of Jupiter's moons, may hide a liquid ocean beneath its ice.",
    ],
  },
  {
    name: "Saturn",
    slug: "saturn",
    type: "gas_giant",
    description: "A gas giant with the most spectacular ring system in the Solar System.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg",
    massKg: 5.68e26,
    diameterKm: 116460,
    gravityMs2: 10.44,
    distanceFromSunAu: 9.537,
    orbitalPeriodDays: 10759,
    rotationPeriodHours: 10.7,
    avgTempCelsius: -140,
    atmosphere: ["H2", "He", "CH4"],
    numberOfMoons: 146,
    hasRings: true,
    discoveredBy: "Known in antiquity",
    isVisible: true,
    aiFunFacts: [
      "Saturn is less dense than water, so it would float in a large enough ocean.",
      "Saturn's rings are made mostly of ice and rock particles.",
      "Titan, Saturn's largest moon, has a denser atmosphere than Earth.",
    ],
  },
  {
    name: "Uranus",
    slug: "uranus",
    type: "ice_giant",
    description: "An ice giant that rotates on its side with an extreme axial tilt.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Uranus2.jpg",
    massKg: 8.68e25,
    diameterKm: 50724,
    gravityMs2: 8.69,
    distanceFromSunAu: 19.19,
    orbitalPeriodDays: 30687,
    rotationPeriodHours: 17.2,
    avgTempCelsius: -195,
    atmosphere: ["H2", "He", "CH4"],
    numberOfMoons: 28,
    hasRings: true,
    discoveredBy: "William Herschel",
    discoveryYear: 1781,
    isVisible: true,
    aiFunFacts: [
      "Uranus is tilted so far that its seasons last for decades.",
      "Uranus has the coldest planetary atmosphere measured in the Solar System.",
      "Uranus has faint, dark rings and many icy moons.",
    ],
  },
  {
    name: "Neptune",
    slug: "neptune",
    type: "ice_giant",
    description: "The farthest major planet, with some of the fastest winds in the Solar System.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Neptune_Full.jpg",
    massKg: 1.02e26,
    diameterKm: 49244,
    gravityMs2: 11.15,
    distanceFromSunAu: 30.07,
    orbitalPeriodDays: 60190,
    rotationPeriodHours: 16.1,
    avgTempCelsius: -200,
    atmosphere: ["H2", "He", "CH4"],
    numberOfMoons: 16,
    hasRings: true,
    discoveredBy: "Urbain Le Verrier & John Adams",
    discoveryYear: 1846,
    isVisible: true,
    aiFunFacts: [
      "Winds on Neptune can exceed 2,000 km/h, among the fastest in the Solar System.",
      "Neptune takes about 165 Earth years to complete one orbit around the Sun.",
      "Triton, Neptune's largest moon, orbits backward and may be a captured Kuiper Belt object.",
    ],
  },
];

async function main() {
  for (const planet of planets) {
    await prisma.planet.upsert({
      where: { slug: planet.slug },
      update: planet,
      create: planet,
    });
  }

  const count = await prisma.planet.count({ where: { isVisible: true } });
  console.log(`Synced ${planets.length} planets. Visible planets in database: ${count}.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
