import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import {
  ArrowLeft,
  Loader2,
  Play,
} from "lucide-react";
import { Starfield } from "../components/lovable/Starfield";
import { PlanetCinematic } from "../components/lovable/PlanetCinematic";
import { getPlanet } from "../lib/planets";
import { getPlanetBySlug } from "../services/planet.api";

const FALLBACK_IMAGE =
  "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1400&q=85";

const PLANET_BRIEFING = {
  mercury: [
    "Mercury is the closest planet to the Sun and completes an orbit in only 88 Earth days.",
    "Its surface is covered with impact craters because it has almost no atmosphere to burn incoming debris.",
    "Daytime temperatures can soar above 430 C, while nights can fall below -180 C.",
    "A solar day on Mercury lasts far longer than its year because the planet rotates very slowly.",
    "Despite the heat, permanently shadowed polar craters may preserve water ice.",
    "Its oversized iron core suggests Mercury lost much of its outer rock early in solar system history.",
  ],
  venus: [
    "Venus is similar to Earth in size, but its atmosphere makes it one of the most hostile worlds known.",
    "Thick carbon dioxide traps heat in a runaway greenhouse effect, pushing the surface near 465 C.",
    "Clouds of sulfuric acid hide the ground from visible light and reflect sunlight brilliantly.",
    "The planet rotates backward compared with most planets, and one Venus day is longer than its year.",
    "Surface pressure is about 90 times Earth's, similar to being deep under an ocean.",
    "Studying Venus helps scientists understand climate feedbacks and the limits of planetary habitability.",
  ],
  earth: [
    "Earth is the only known planet with stable surface oceans and confirmed life.",
    "Its atmosphere is rich in nitrogen and oxygen, shielding the surface while allowing liquid water to persist.",
    "Plate tectonics recycles crust, builds mountains, drives volcanism, and helps regulate long-term climate.",
    "The Moon stabilizes Earth's axial tilt and creates tides that shape coastlines and marine ecosystems.",
    "A magnetic field generated by the outer core deflects much of the solar wind.",
    "From orbit, clouds, oceans, continents, ice, and city lights reveal a planet that is geologically and biologically alive.",
  ],
  mars: [
    "Mars is a cold desert world with iron-rich dust that gives it its red color.",
    "Ancient valleys, deltas, and minerals show that liquid water once flowed across its surface.",
    "Olympus Mons is the largest volcano in the solar system, rising about 22 kilometers high.",
    "Valles Marineris stretches thousands of kilometers, forming a canyon system far larger than Earth's Grand Canyon.",
    "Its thin carbon dioxide atmosphere cannot keep the surface warm for long.",
    "Mars remains a key target for studying past habitability and future human exploration.",
  ],
  jupiter: [
    "Jupiter is the largest planet in the solar system and contains more mass than all other planets combined.",
    "It is mostly hydrogen and helium, with no solid surface like the terrestrial planets.",
    "The Great Red Spot is a giant storm system that has persisted for centuries.",
    "Powerful belts, zones, lightning, and jet streams make Jupiter's atmosphere extremely dynamic.",
    "Its strong magnetic field traps intense radiation around the planet.",
    "Major moons such as Europa, Ganymede, Callisto, and Io are worlds of major scientific interest.",
  ],
  saturn: [
    "Saturn is best known for its wide, bright ring system made mostly of water-ice particles.",
    "The planet is a gas giant with a low average density, lower than water.",
    "Its rings are thin compared with their width, but they contain countless particles from dust to boulder size.",
    "Saturn's moon Titan has a dense atmosphere and lakes of liquid methane and ethane.",
    "Enceladus sprays water-rich plumes from a subsurface ocean through cracks in its icy crust.",
    "The Saturn system is one of the strongest places to study moons, rings, and planetary evolution together.",
  ],
  uranus: [
    "Uranus is an ice giant with a pale cyan color caused by methane absorbing red light.",
    "It rotates on its side, likely because of a massive collision early in its history.",
    "Its extreme axial tilt creates unusual seasons that last for decades.",
    "The atmosphere contains hydrogen, helium, and methane above deeper icy materials.",
    "Uranus has faint rings and a family of moons named after literary characters.",
    "Because it has been visited only once by Voyager 2, many details about its interior remain uncertain.",
  ],
  neptune: [
    "Neptune is the farthest known major planet and receives very little sunlight.",
    "Its deep blue color comes from methane and other atmospheric chemistry.",
    "The planet has some of the fastest winds measured in the solar system, exceeding 2,000 km/h.",
    "Dark storms appear and fade in its atmosphere, revealing active weather far from the Sun.",
    "Triton, Neptune's largest moon, orbits backward and may be a captured Kuiper Belt object.",
    "Neptune marks the outer edge of the classical planet system and links planetary science with the distant icy frontier.",
  ],
};

function formatNumber(value, options = {}) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return null;
  return new Intl.NumberFormat("en-US", options).format(numeric);
}

function formatCompact(value, suffix = "") {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return "Unknown";
  return `${new Intl.NumberFormat("en-US", {
    notation: "compact",
    maximumFractionDigits: 2,
  }).format(numeric)}${suffix}`;
}

function formatKm(value) {
  const formatted = formatNumber(value);
  return formatted ? `${formatted} km` : "Unknown";
}

function formatAu(value) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return "Unknown";
  return `${formatNumber(numeric, { maximumFractionDigits: 3 })} AU`;
}

function formatBoolean(value) {
  if (value === true) return "Yes";
  if (value === false) return "No";
  return "Unknown";
}

function localPlanetAsDetail(local) {
  return {
    slug: local.slug,
    name: local.name,
    type: "Planet",
    description: local.description,
    imageUrl: local.image,
    numberOfMoons: local.moons,
    aiFunFacts: PLANET_BRIEFING[local.slug] || [],
    atmosphere: [],
  };
}

function normalizePlanet(raw, slug) {
  const local = getPlanet(slug);
  if (!raw) return null;
  const curatedFacts = PLANET_BRIEFING[slug] || [];

  return {
    ...raw,
    slug: raw.slug || slug,
    name: raw.name || local?.name || "Unknown planet",
    description: local?.description || raw.description || "No description is available for this planet yet.",
    imageUrl: local?.image || raw.imageUrl || FALLBACK_IMAGE,
    aiFunFacts: curatedFacts.length ? curatedFacts : Array.isArray(raw.aiFunFacts) ? raw.aiFunFacts : [],
    atmosphere: Array.isArray(raw.atmosphere) ? raw.atmosphere : [],
  };
}

function formatDay(hours, fallback = "Unknown") {
  const numeric = Number(hours);
  if (!Number.isFinite(numeric)) return fallback;
  if (numeric >= 48) return `${formatNumber(Math.round(numeric / 24))} days`;
  return `${formatNumber(numeric, { maximumFractionDigits: 1 })} hours`;
}

function formatYear(days, fallback = "Unknown") {
  const numeric = Number(days);
  if (!Number.isFinite(numeric)) return fallback;
  if (numeric >= 3650) return `${formatNumber(Number((numeric / 365.25).toFixed(1)))} years`;
  return `${formatNumber(numeric, { maximumFractionDigits: 1 })} days`;
}

function toCinematicPlanet(planet, local) {
  return {
    slug: planet.slug,
    name: planet.name,
    tagline: local?.tagline || planet.type || "Planetary profile",
    description: planet.description,
    image: local?.image || planet.imageUrl || FALLBACK_IMAGE,
    accent: local?.accent || "from-sky-400 to-blue-700",
    diameter: planet.diameterKm ? formatKm(planet.diameterKm) : local?.diameter || "Unknown",
    day: formatDay(planet.rotationPeriodHours, local?.day || "Unknown"),
    year: formatYear(planet.orbitalPeriodDays, local?.year || "Unknown"),
    moons: planet.numberOfMoons ?? local?.moons ?? 0,
    distance: planet.distanceFromSunAu ? formatAu(planet.distanceFromSunAu) : local?.distance || "Unknown",
  };
}

function PlanetSpaceXProfile({ planet, cinematicPlanet }) {
  const briefing = PLANET_BRIEFING[planet.slug] || planet.aiFunFacts || [];
  const stats = [
    { label: "Diameter", value: planet.diameterKm ? formatKm(planet.diameterKm) : cinematicPlanet.diameter },
    { label: "Day", value: cinematicPlanet.day },
    { label: "Year", value: cinematicPlanet.year },
    { label: "Moon", value: `${cinematicPlanet.moons}` },
    { label: "Distance", value: cinematicPlanet.distance },
  ];

  const tableRows = [
    { label: "Mass", value: formatCompact(planet.massKg, " kg") },
    { label: "Gravity", value: planet.gravityMs2 != null ? `${formatNumber(planet.gravityMs2, { maximumFractionDigits: 2 })} m/s2` : "9.81 m/s2" },
    { label: "Average temperature", value: planet.avgTempCelsius != null ? `${formatNumber(planet.avgTempCelsius)} C` : "15 C" },
    { label: "Orbital period", value: cinematicPlanet.year },
    { label: "Rotation period", value: cinematicPlanet.day },
    { label: "Has rings", value: formatBoolean(planet.hasRings) },
  ];

  return (
    <section id="planet-profile" className="relative z-10 border-t border-white/10 bg-[#020712]/72 px-6 py-24 md:px-12 lg:px-16">
      <div className="mx-auto max-w-7xl">
        <div className="grid gap-12 lg:grid-cols-[minmax(0,0.95fr)_minmax(380px,0.72fr)] lg:items-end">
          <div>
            <p className="text-[11px] font-bold uppercase tracking-[0.36em] text-[#6ecbff]/72">{planet.name} profile</p>
            <h2 className="mt-5 max-w-5xl font-display text-5xl font-semibold uppercase leading-[0.95] tracking-[-0.02em] text-white md:text-7xl">
              Observing {planet.name} as a mission profile.
            </h2>
            <p className="mt-8 max-w-3xl text-lg font-light leading-9 text-slate-200/82 md:text-xl">
              {planet.description}
            </p>
          </div>

          <div className="grid grid-cols-2 border-y border-white/18 md:grid-cols-5 lg:grid-cols-1">
            {stats.map((item) => (
              <div key={item.label} className="border-b border-white/12 py-5 last:border-b-0 md:border-b-0 md:border-r md:border-white/12 md:px-5 md:last:border-r-0 lg:border-r-0 lg:px-0">
                <p className="text-[10px] font-bold uppercase tracking-[0.24em] text-slate-400">{item.label}</p>
                <p className="mt-2 text-3xl font-semibold tracking-[-0.03em] text-white">{item.value}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-20 grid gap-10 lg:grid-cols-[0.72fr_1fr]">
          <div className="min-h-[520px] overflow-hidden bg-black shadow-[0_28px_120px_rgba(0,0,0,0.45)]">
            <img
              src={planet.imageUrl || cinematicPlanet.image}
              alt={planet.name}
              className="h-full min-h-[520px] w-full object-cover"
            />
          </div>

          <div className="grid content-center gap-10">
            <section>
              <p className="text-[11px] font-bold uppercase tracking-[0.34em] text-[#6ecbff]/72">AI facts</p>
              <h3 className="mt-4 font-display text-4xl font-semibold uppercase tracking-[-0.02em] text-white md:text-6xl">
                Observations worth pausing for.
              </h3>
              <div className="mt-8 grid gap-4">
                {(planet.aiFunFacts?.length ? planet.aiFunFacts : briefing).slice(0, 4).map((fact, index) => (
                  <article key={`${fact}-${index}`} className="border-t border-white/14 pt-4">
                    <p className="text-[10px] font-bold uppercase tracking-[0.28em] text-slate-500">{String(index + 1).padStart(2, "0")}</p>
                    <p className="mt-2 text-lg leading-8 text-slate-200/82">{fact}</p>
                  </article>
                ))}
              </div>
            </section>

            <section className="border-t border-white/14 pt-8">
              <p className="text-[11px] font-bold uppercase tracking-[0.34em] text-[#6ecbff]/72">Mission profile</p>
              <div className="mt-6 grid gap-4">
                {(briefing.length ? briefing : [planet.description]).map((line) => (
                  <p key={line} className="max-w-4xl text-lg font-light leading-9 text-slate-200/78">
                    {line}
                  </p>
                ))}
              </div>
            </section>
          </div>
        </div>

        <div className="mt-20 grid gap-12 lg:grid-cols-[0.9fr_1fr]">
          <section>
            <p className="text-[11px] font-bold uppercase tracking-[0.34em] text-[#6ecbff]/72">Atmosphere</p>
            <h3 className="mt-4 font-display text-4xl font-semibold uppercase tracking-[-0.02em] text-white md:text-6xl">
              The envelope around the world.
            </h3>
            <div className="mt-7 flex flex-wrap gap-3">
              {(planet.atmosphere?.length ? planet.atmosphere : ["N2", "O2", "Ar", "CO2"]).map((item) => (
                  <span key={item} className="border border-white/18 px-5 py-3 text-base font-semibold uppercase tracking-[0.18em] text-white/82">
                  {item}
                </span>
              ))}
            </div>
          </section>

          <section>
            <p className="text-[11px] font-bold uppercase tracking-[0.34em] text-[#6ecbff]/72">Planet data</p>
            <div className="mt-5 border-y border-white/16">
              {tableRows.map((row) => (
                <div key={row.label} className="grid grid-cols-[1fr_auto] gap-4 border-b border-white/12 py-4 last:border-b-0">
                  <span className="text-base font-semibold uppercase tracking-[0.18em] text-slate-400">{row.label}</span>
                  <span className="text-right text-base font-semibold text-white">{row.value}</span>
                </div>
              ))}
            </div>
            <Link
              to={`/planets/${planet.slug}/facts`}
              className="mt-8 inline-flex border-2 border-[#6ecbff]/60 bg-[#6ecbff]/10 px-7 py-3 text-xs font-bold uppercase tracking-[0.22em] text-white transition hover:border-[#9bd5ff] hover:bg-[#6ecbff]/20 hover:text-white"
            >
              Read NASA-style facts
            </Link>
          </section>
        </div>
      </div>
    </section>
  );
}

function LoadingState() {
  return (
    <main className="relative grid min-h-screen place-items-center bg-[#08111f] px-6 text-center text-white">
      <Starfield />
      <div className="relative z-10">
        <Loader2 className="mx-auto h-10 w-10 animate-spin text-[#3fa9f5]" />
        <p className="mt-4 text-sm text-slate-300">Loading planet details...</p>
      </div>
    </main>
  );
}

function ErrorState({ title, message, onRetry }) {
  return (
    <main className="relative grid min-h-screen place-items-center bg-[#08111f] px-6 text-center text-white">
      <Starfield />
      <div className="relative z-10 max-w-md rounded-3xl border border-white/10 bg-[#0d1b2a]/75 p-8 shadow-[0_24px_90px_rgba(0,0,0,0.28)] backdrop-blur-xl">
        <p className="text-[10px] uppercase tracking-[0.35em] text-[#9bd5ff]">Planet detail</p>
        <h1 className="mt-4 font-display text-3xl font-light">{title}</h1>
        <p className="mt-4 text-sm leading-relaxed text-slate-300">{message}</p>
        <div className="mt-6 flex flex-wrap justify-center gap-3">
          {onRetry ? (
            <button
              type="button"
              onClick={onRetry}
              className="rounded-full border border-[#3fa9f5]/30 bg-[#3fa9f5]/15 px-5 py-2 text-sm text-[#d6efff] transition hover:bg-[#3fa9f5]/25"
            >
              Retry
            </button>
          ) : null}
          <Link
            to="/planets"
            className="rounded-full border border-white/10 bg-white/[0.04] px-5 py-2 text-sm text-slate-200 transition hover:bg-white/10"
          >
            Back to Planets
          </Link>
        </div>
      </div>
    </main>
  );
}

export default function PlanetDetail() {
  const { slug } = useParams();
  const [planet, setPlanet] = useState(null);
  const [status, setStatus] = useState("loading");
  const [error, setError] = useState("");

  const localPlanet = useMemo(() => getPlanet(slug), [slug]);

  async function loadPlanet() {
    if (!slug) {
      setStatus("not-found");
      return;
    }

    setStatus("loading");
    setError("");

    try {
      const data = await getPlanetBySlug(slug);
      setPlanet(normalizePlanet(data, slug));
      setStatus("ready");
    } catch (err) {
      const statusCode = err.response?.status;
      if (statusCode === 404 && localPlanet) {
        setPlanet(localPlanetAsDetail(localPlanet));
        setStatus("ready");
        return;
      }
      setError(err.response?.data?.message || err.message || "Could not load this planet.");
      setStatus(statusCode === 404 ? "not-found" : "error");
    }
  }

  useEffect(() => {
    loadPlanet();
  }, [slug]);

  if (status === "loading") return <LoadingState />;

  if (status === "not-found") {
    return (
      <ErrorState
        title="Planet not found"
        message="The requested planet could not be found in the CosmoVision database."
      />
    );
  }

  if (status === "error") {
    return (
      <ErrorState
        title="Unable to load planet"
        message={error}
        onRetry={loadPlanet}
      />
    );
  }

  const viewPlanet = normalizePlanet(planet, slug);
  const cinematicPlanet = toCinematicPlanet(viewPlanet, localPlanet);
  const heroKicker = viewPlanet.slug === "earth" ? "The Blue Planet" : cinematicPlanet.tagline;

  return (
    <main className="relative min-h-screen overflow-hidden bg-[#08111f] text-white">
      <Starfield />
      <PlanetCinematic planet={cinematicPlanet} />
      <div className="pointer-events-none fixed inset-0 z-0 bg-[radial-gradient(circle_at_72%_38%,rgba(63,169,245,0.17),transparent_32%),radial-gradient(circle_at_16%_20%,rgba(11,61,145,0.36),transparent_36%),linear-gradient(180deg,rgba(8,17,31,0.14),#08111f_88%)]" />

      <section className="relative z-10 grid min-h-screen items-center px-6 pb-16 pt-28 md:px-12 lg:grid-cols-[minmax(0,0.9fr)_minmax(360px,1.1fr)] lg:px-16">
        <div className="max-w-xl">
          <Link
            to="/planets"
            className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.035] px-4 py-2 text-xs uppercase tracking-[0.22em] text-slate-200/78 backdrop-blur-sm transition hover:border-[#6ecbff]/45 hover:bg-[#6ecbff]/10 hover:text-white"
          >
            <ArrowLeft className="h-4 w-4" />
            Planets
          </Link>
          <p className="mt-14 font-display text-[11px] uppercase tracking-[0.48em] text-[#cdefff]/72">
            {heroKicker}
          </p>
          <h1 className="mt-3 font-display text-7xl font-light uppercase leading-[0.82] tracking-[0.04em] text-white drop-shadow-[0_18px_70px_rgba(0,0,0,0.75)] md:text-8xl lg:text-9xl">
            {viewPlanet.name}
          </h1>
          <div className="mt-7 h-px w-24 bg-[#6ecbff]/80 shadow-[0_0_18px_rgba(110,203,255,0.55)]" />
          <p className="mt-8 max-w-lg text-base font-light leading-relaxed text-slate-200/74 md:text-lg">
            {viewPlanet.description}
          </p>
          <div className="mt-10 flex flex-wrap items-center gap-4">
            <Link
              to={`/planets/${viewPlanet.slug}/facts`}
              className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#6ecbff]/35 bg-[#6ecbff]/10 px-7 text-xs font-light uppercase tracking-[0.24em] text-foreground shadow-[0_0_28px_rgba(110,203,255,0.12)] transition hover:-translate-y-0.5 hover:border-[#6ecbff]/55 hover:bg-[#6ecbff]/16"
            >
              Learn more
            </Link>
            <a
              href="#planet-profile"
              aria-label={`Open ${viewPlanet.name} profile`}
              className="inline-flex size-12 items-center justify-center rounded-full border border-[#d6efff]/30 bg-[#d6efff]/12 text-[#eaf6ff] shadow-[0_0_28px_rgba(110,203,255,0.18)] transition hover:-translate-y-0.5 hover:border-[#d6efff]/55 hover:bg-[#d6efff]/20"
            >
              <Play className="ml-0.5 h-4 w-4 fill-current" />
            </a>
          </div>
          <p className="mt-8 font-display text-[10px] uppercase tracking-[0.32em] text-slate-300/48">
            {cinematicPlanet.distance} from the Sun
          </p>
        </div>
        <div className="pointer-events-none hidden min-h-[520px] lg:block" aria-hidden="true" />
      </section>

      <PlanetSpaceXProfile planet={viewPlanet} cinematicPlanet={cinematicPlanet} />
    </main>
  );
}
