export const planets = [
  {
    id: "mercury",
    name: "Mercury",
    vietnamese: "Sao Thuy",
    image: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?auto=format&fit=crop&w=900&q=80",
    color: "#a3a3a3",
    moons: 0,
    temperature: "167 C",
    distanceFromSun: "57.9 million km",
    diameter: "4,879 km",
    description: "The smallest planet and the closest world to the Sun.",
    facts: ["A year lasts only 88 Earth days.", "Its surface is covered with impact craters."],
  },
  {
    id: "venus",
    name: "Venus",
    vietnamese: "Sao Kim",
    image: "https://images.unsplash.com/photo-1614314107768-6018061b5b72?auto=format&fit=crop&w=900&q=80",
    color: "#f59e0b",
    moons: 0,
    temperature: "464 C",
    distanceFromSun: "108.2 million km",
    diameter: "12,104 km",
    description: "A hot, cloud-covered planet with a thick carbon dioxide atmosphere.",
    facts: ["It rotates in the opposite direction to most planets.", "Its surface pressure is extreme."],
  },
  {
    id: "earth",
    name: "Earth",
    vietnamese: "Trai Dat",
    image: "https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?auto=format&fit=crop&w=900&q=80",
    color: "#38bdf8",
    moons: 1,
    temperature: "15 C",
    distanceFromSun: "149.6 million km",
    diameter: "12,742 km",
    description: "Our ocean world, currently the only known planet with life.",
    facts: ["About 71% of the surface is covered by water.", "Its magnetic field helps shield life from solar wind."],
  },
  {
    id: "mars",
    name: "Mars",
    vietnamese: "Sao Hoa",
    image: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=900&q=80",
    color: "#ef4444",
    moons: 2,
    temperature: "-65 C",
    distanceFromSun: "227.9 million km",
    diameter: "6,779 km",
    description: "The red planet, home to giant volcanoes and ancient river valleys.",
    facts: ["Olympus Mons is the largest volcano in the Solar System.", "Its moons are Phobos and Deimos."],
  },
  {
    id: "jupiter",
    name: "Jupiter",
    vietnamese: "Sao Moc",
    image: "https://images.unsplash.com/photo-1630839437035-dac17da580d0?auto=format&fit=crop&w=900&q=80",
    color: "#f97316",
    moons: 95,
    temperature: "-110 C",
    distanceFromSun: "778.5 million km",
    diameter: "139,820 km",
    description: "The largest planet, a gas giant famous for the Great Red Spot.",
    facts: ["It has the strongest planetary magnetic field.", "The Great Red Spot is a long-lived storm."],
  },
  {
    id: "saturn",
    name: "Saturn",
    vietnamese: "Sao Tho",
    image: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&w=900&q=80",
    color: "#facc15",
    moons: 146,
    temperature: "-140 C",
    distanceFromSun: "1.43 billion km",
    diameter: "116,460 km",
    description: "A ringed gas giant with icy rings and many moons.",
    facts: ["Its rings are mostly ice and rock.", "Titan has a dense atmosphere."],
  },
  {
    id: "uranus",
    name: "Uranus",
    vietnamese: "Sao Thien Vuong",
    image: "https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?auto=format&fit=crop&w=900&q=80",
    color: "#67e8f9",
    moons: 27,
    temperature: "-195 C",
    distanceFromSun: "2.87 billion km",
    diameter: "50,724 km",
    description: "An ice giant that rotates on its side.",
    facts: ["Its axial tilt is about 98 degrees.", "Methane gives it a blue-green color."],
  },
  {
    id: "neptune",
    name: "Neptune",
    vietnamese: "Sao Hai Vuong",
    image: "https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?auto=format&fit=crop&w=900&q=80",
    color: "#2563eb",
    moons: 14,
    temperature: "-200 C",
    distanceFromSun: "4.50 billion km",
    diameter: "49,244 km",
    description: "A distant blue ice giant with powerful winds.",
    facts: ["It was predicted mathematically before it was observed.", "Triton is its largest moon."],
  },
];

export const constellations = [
  {
    id: "orion",
    name: "Orion",
    vietnamese: "Tho San",
    image: "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=900&q=80",
    color: "#60a5fa",
    season: "Dong",
    hemisphere: "Both",
    stars: 7,
    brightestStar: "Rigel",
    description: "One of the easiest constellations to recognize, marked by Orion's Belt.",
    mythology: "In Greek mythology, Orion was a mighty hunter placed among the stars.",
  },
  {
    id: "ursa-major",
    name: "Ursa Major",
    vietnamese: "Dai Hung",
    image: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=900&q=80",
    color: "#c084fc",
    season: "Quanh nam",
    hemisphere: "Northern",
    stars: 7,
    brightestStar: "Alioth",
    description: "A large northern constellation containing the Big Dipper asterism.",
    mythology: "Often linked to the myth of Callisto, transformed into a bear and placed in the sky.",
  },
  {
    id: "scorpius",
    name: "Scorpius",
    vietnamese: "Bo Cap",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80",
    color: "#f87171",
    season: "He",
    hemisphere: "Southern",
    stars: 13,
    brightestStar: "Antares",
    description: "A striking constellation shaped like a scorpion, bright in summer skies.",
    mythology: "The scorpion is said to have pursued Orion in ancient Greek star lore.",
  },
];
